// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThueSan_UNETI04_DHTI17A4HN.Data;

#nullable disable

namespace QuanLyThueSan_UNETI04_DHTI17A4HN.Migrations
{
    [DbContext(typeof(QuanLySanContext))]
    partial class QuanLySanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", b =>
                {
                    b.Property<int>("MaDatSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatSan"));

                    b.Property<decimal>("DonGiaSanDuKien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgaySuDung")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ThoiDiemNhanThucTe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiDiemTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDatSan");

                    b.HasIndex("MaSan", "NgaySuDung", "TrangThai");

                    b.ToTable("DatSans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu")
                        .IsUnique();

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", b =>
                {
                    b.Property<int>("MaSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSan"));

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("MaSan");

                    b.ToTable("SanTheThaos");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SuDungDichVu", b =>
                {
                    b.Property<int>("MaSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuDung"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDatSan")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianThem")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSuDung");

                    b.HasIndex("MaDatSan");

                    b.HasIndex("MaDichVu");

                    b.ToTable("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", "San")
                        .WithMany("DatSans")
                        .HasForeignKey("MaSan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("San");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SuDungDichVu", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", "DatSan")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDatSan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DichVu", "DichVu")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatSan");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DichVu", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", b =>
                {
                    b.Navigation("DatSans");
                });
#pragma warning restore 612, 618
        }
    }
}
