// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThueSan_UNETI04_DHTI17A4HN.Data;

#nullable disable

namespace QuanLyThueSan_UNETI04_DHTI17A4HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930020528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.BangGia", b =>
                {
                    b.Property<int>("MaBangGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangGia"));

                    b.Property<decimal>("DonGiaMoiGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("MaSan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDungDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayApDungTu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBangGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBangGia");

                    b.HasIndex("MaSan");

                    b.ToTable("BangGias");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", b =>
                {
                    b.Property<int>("MaDatSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatSan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDatSan");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaSan");

                    b.ToTable("DatSans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu")
                        .IsUnique();

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique();

                    b.ToTable("KhuVucs");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.LoaiSan", b =>
                {
                    b.Property<int>("MaLoaiSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSan"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiSan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiSan");

                    b.HasIndex("TenLoaiSan")
                        .IsUnique();

                    b.ToTable("LoaiSans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", b =>
                {
                    b.Property<int>("MaSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSan"));

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiSan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSan");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaLoaiSan");

                    b.ToTable("SanTheThaos");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SuDungDichVu", b =>
                {
                    b.Property<int>("MaSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuDung"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDatSan")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianThem")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSuDung");

                    b.HasIndex("MaDatSan");

                    b.HasIndex("MaDichVu");

                    b.ToTable("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDatSan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienSan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDatSan")
                        .IsUnique();

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.BangGia", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", "SanTheThao")
                        .WithMany("BangGias")
                        .HasForeignKey("MaSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanTheThao");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhachHang", "KhachHang")
                        .WithMany("DatSans")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", "SanTheThao")
                        .WithMany("DatSans")
                        .HasForeignKey("MaSan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanTheThao");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhachHang", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhuVuc", "KhuVuc")
                        .WithMany("SanTheThaos")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.LoaiSan", "LoaiSan")
                        .WithMany("SanTheThaos")
                        .HasForeignKey("MaLoaiSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVuc");

                    b.Navigation("LoaiSan");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SuDungDichVu", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", "DatSan")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDatSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DichVu", "DichVu")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatSan");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", "DatSan")
                        .WithOne("ThanhToan")
                        .HasForeignKey("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.ThanhToan", "MaDatSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatSan");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DatSan", b =>
                {
                    b.Navigation("SuDungDichVus");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.DichVu", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhachHang", b =>
                {
                    b.Navigation("DatSans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.KhuVuc", b =>
                {
                    b.Navigation("SanTheThaos");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.LoaiSan", b =>
                {
                    b.Navigation("SanTheThaos");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.SanTheThao", b =>
                {
                    b.Navigation("BangGias");

                    b.Navigation("DatSans");
                });

            modelBuilder.Entity("QuanLyThueSan_UNETI04_DHTI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
